name: deploy to lambda
on: [push]
jobs:

  deploy_zip:
    name: deploy lambda function
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.20.x]
    steps:
      - name: checkout source code
        uses: actions/checkout@v3
      - name: Zip code
        run: |
          zip deployment.zip main
      - name: default deploy
        uses: appleboy/lambda-action@v0.1.9
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: InteractsWithTelegram
          zip_file: deployment.zip
          memory_size: 128
          timeout: 10
          handler: Telegram
          # role: arn:aws:iam::xxxxxxxxxxx:role/test1234
          runtime: nodejs16.x
          debug: true
          environment: TELEGRAM_TOKEN=${{ secrets.TG_TOKEN }},APP_URL=${{ secrets.APP_URL }}
